name: Prerelease Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Determine Version Number
      id: version
      run: |
        YEAR=$(date +%Y)
        LAST_VERSION_TAG=$(git tag -l --sort=-creatordate|grep -v 'pre'|head -n 1)
        LAST_MAJOR=$(echo $LAST_VERSION_TAG|sed -E 's/^[^\.]+\.//g;s/\..+//g')
        MAJOR=$(($LAST_MAJOR+1))
        MINOR=$(git log --oneline HEAD...$LAST_VERSION_TAG|wc -l)
        echo "Year: "$YEAR
        echo "Last Version: "$LAST_VERSION_TAG
        echo "Last Major: "$LAST_MAJOR
        echo $YEAR.$MAJOR.$MINOR-pre
        echo "TAG_NAME=$YEAR.$MAJOR.$MINOR-pre" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        name: Prerelease - ${{ steps.version.outputs.TAG_NAME }}
        draft: true
        make_latest: false
        token: ${{ secrets.GIT_TOKEN }}
        files: |
          build/cekwebhooks-linux-amd64.so
          build/cekwebhooks-linux-arm-7.so
          build/cekwebhooks-linux-arm64.so
