name: Prerelease Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: build/cekwebhooks-linux-*
        retention-days: 1

    - name: Determine Version Number
      id: version
      run: |
        echo "TAG_NAME=$(date +%Y).$((1+$(git tag -l --sort=-creatordate|grep -v 'pre'|head -n 1|sed -E 's/^[^\.]+\.//g;s/\..+//g'))).$(git log --oneline HEAD...$(git tag -l --sort=-creatordate|grep -v 'pre'|head -n 1)|wc -l)-pre" >> $GITHUB_OUTPUT
    - name: Release
        uses: softprops/action-gh-release@v2
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        name: Prerelease - ${{ steps.version.outputs.TAG_NAME }}
        draft: true
        make_latest: false
        with:
          files: |
            build/cekwebhooks-linux-amd64.so
            build/cekwebhooks-linux-arm-7.so
            build/cekwebhooks-linux-arm64.so
